//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplyLeave", Namespace="http://schemas.datacontract.org/2004/07/HRMDAL.Entites")]
    [System.SerializableAttribute()]
    public partial class ApplyLeave : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LeaveIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LeaveTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NofDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TodateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpID {
            get {
                return this.EmpIDField;
            }
            set {
                if ((this.EmpIDField.Equals(value) != true)) {
                    this.EmpIDField = value;
                    this.RaisePropertyChanged("EmpID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((this.FromDateField.Equals(value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveID {
            get {
                return this.LeaveIDField;
            }
            set {
                if ((this.LeaveIDField.Equals(value) != true)) {
                    this.LeaveIDField = value;
                    this.RaisePropertyChanged("LeaveID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveTypeID {
            get {
                return this.LeaveTypeIDField;
            }
            set {
                if ((this.LeaveTypeIDField.Equals(value) != true)) {
                    this.LeaveTypeIDField = value;
                    this.RaisePropertyChanged("LeaveTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NofDays {
            get {
                return this.NofDaysField;
            }
            set {
                if ((this.NofDaysField.Equals(value) != true)) {
                    this.NofDaysField = value;
                    this.RaisePropertyChanged("NofDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Todate {
            get {
                return this.TodateField;
            }
            set {
                if ((this.TodateField.Equals(value) != true)) {
                    this.TodateField = value;
                    this.RaisePropertyChanged("Todate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IApplyLeave")]
    public interface IApplyLeave {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplyLeave/ApplyLeav", ReplyAction="http://tempuri.org/IApplyLeave/ApplyLeavResponse")]
        void ApplyLeav(HumanResourceApplication.ServiceReference1.ApplyLeave App);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplyLeave/GetLeaveQuota", ReplyAction="http://tempuri.org/IApplyLeave/GetLeaveQuotaResponse")]
        System.Data.DataSet GetLeaveQuota(int empId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplyLeave/GetLeaveHistory", ReplyAction="http://tempuri.org/IApplyLeave/GetLeaveHistoryResponse")]
        System.Data.DataSet GetLeaveHistory(int empId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplyLeave/GetAllLeavesPending", ReplyAction="http://tempuri.org/IApplyLeave/GetAllLeavesPendingResponse")]
        System.Data.DataSet GetAllLeavesPending();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplyLeave/ApproveLeaves", ReplyAction="http://tempuri.org/IApplyLeave/ApproveLeavesResponse")]
        void ApproveLeaves(int empid, System.DateTime fromdate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplyLeaveChannel : HumanResourceApplication.ServiceReference1.IApplyLeave, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplyLeaveClient : System.ServiceModel.ClientBase<HumanResourceApplication.ServiceReference1.IApplyLeave>, HumanResourceApplication.ServiceReference1.IApplyLeave {
        
        public ApplyLeaveClient() {
        }
        
        public ApplyLeaveClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplyLeaveClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplyLeaveClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplyLeaveClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ApplyLeav(HumanResourceApplication.ServiceReference1.ApplyLeave App) {
            base.Channel.ApplyLeav(App);
        }
        
        public System.Data.DataSet GetLeaveQuota(int empId) {
            return base.Channel.GetLeaveQuota(empId);
        }
        
        public System.Data.DataSet GetLeaveHistory(int empId) {
            return base.Channel.GetLeaveHistory(empId);
        }
        
        public System.Data.DataSet GetAllLeavesPending() {
            return base.Channel.GetAllLeavesPending();
        }
        
        public void ApproveLeaves(int empid, System.DateTime fromdate) {
            base.Channel.ApproveLeaves(empid, fromdate);
        }
    }
}
