//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceApplication.EmpSea {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeSearch", Namespace="http://schemas.datacontract.org/2004/07/HRMDAL.Entites")]
    [System.SerializableAttribute()]
    public partial class EmployeeSearch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DOJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EFnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cname {
            get {
                return this.CnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CnameField, value) != true)) {
                    this.CnameField = value;
                    this.RaisePropertyChanged("Cname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DOJ {
            get {
                return this.DOJField;
            }
            set {
                if ((this.DOJField.Equals(value) != true)) {
                    this.DOJField = value;
                    this.RaisePropertyChanged("DOJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EFname {
            get {
                return this.EFnameField;
            }
            set {
                if ((object.ReferenceEquals(this.EFnameField, value) != true)) {
                    this.EFnameField = value;
                    this.RaisePropertyChanged("EFname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpID {
            get {
                return this.EmpIDField;
            }
            set {
                if ((this.EmpIDField.Equals(value) != true)) {
                    this.EmpIDField = value;
                    this.RaisePropertyChanged("EmpID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmlpoyeeSeachEditEmp", Namespace="http://schemas.datacontract.org/2004/07/HRMDAL.Entites")]
    [System.SerializableAttribute()]
    public partial class EmlpoyeeSeachEditEmp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dep {
            get {
                return this.DepField;
            }
            set {
                if ((object.ReferenceEquals(this.DepField, value) != true)) {
                    this.DepField = value;
                    this.RaisePropertyChanged("Dep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpID {
            get {
                return this.EmpIDField;
            }
            set {
                if ((this.EmpIDField.Equals(value) != true)) {
                    this.EmpIDField = value;
                    this.RaisePropertyChanged("EmpID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salary", Namespace="http://schemas.datacontract.org/2004/07/HRMDAL.Entites")]
    [System.SerializableAttribute()]
    public partial class Salary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BasicSalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ConvyanceAllwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EducationAllwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MedicalAllwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OtherDeductionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PerformanceAllwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProfessionTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProvidentTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SpecailAllwField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BasicSal {
            get {
                return this.BasicSalField;
            }
            set {
                if ((this.BasicSalField.Equals(value) != true)) {
                    this.BasicSalField = value;
                    this.RaisePropertyChanged("BasicSal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ConvyanceAllw {
            get {
                return this.ConvyanceAllwField;
            }
            set {
                if ((this.ConvyanceAllwField.Equals(value) != true)) {
                    this.ConvyanceAllwField = value;
                    this.RaisePropertyChanged("ConvyanceAllw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EducationAllw {
            get {
                return this.EducationAllwField;
            }
            set {
                if ((this.EducationAllwField.Equals(value) != true)) {
                    this.EducationAllwField = value;
                    this.RaisePropertyChanged("EducationAllw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpID {
            get {
                return this.EmpIDField;
            }
            set {
                if ((this.EmpIDField.Equals(value) != true)) {
                    this.EmpIDField = value;
                    this.RaisePropertyChanged("EmpID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LTA {
            get {
                return this.LTAField;
            }
            set {
                if ((this.LTAField.Equals(value) != true)) {
                    this.LTAField = value;
                    this.RaisePropertyChanged("LTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MedicalAllw {
            get {
                return this.MedicalAllwField;
            }
            set {
                if ((this.MedicalAllwField.Equals(value) != true)) {
                    this.MedicalAllwField = value;
                    this.RaisePropertyChanged("MedicalAllw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OtherDeductions {
            get {
                return this.OtherDeductionsField;
            }
            set {
                if ((this.OtherDeductionsField.Equals(value) != true)) {
                    this.OtherDeductionsField = value;
                    this.RaisePropertyChanged("OtherDeductions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PerformanceAllw {
            get {
                return this.PerformanceAllwField;
            }
            set {
                if ((this.PerformanceAllwField.Equals(value) != true)) {
                    this.PerformanceAllwField = value;
                    this.RaisePropertyChanged("PerformanceAllw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProfessionTax {
            get {
                return this.ProfessionTaxField;
            }
            set {
                if ((this.ProfessionTaxField.Equals(value) != true)) {
                    this.ProfessionTaxField = value;
                    this.RaisePropertyChanged("ProfessionTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProvidentTax {
            get {
                return this.ProvidentTaxField;
            }
            set {
                if ((this.ProvidentTaxField.Equals(value) != true)) {
                    this.ProvidentTaxField = value;
                    this.RaisePropertyChanged("ProvidentTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalID {
            get {
                return this.SalIDField;
            }
            set {
                if ((this.SalIDField.Equals(value) != true)) {
                    this.SalIDField = value;
                    this.RaisePropertyChanged("SalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SpecailAllw {
            get {
                return this.SpecailAllwField;
            }
            set {
                if ((this.SpecailAllwField.Equals(value) != true)) {
                    this.SpecailAllwField = value;
                    this.RaisePropertyChanged("SpecailAllw");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/HRMDAL.Entites")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DOJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DOJ {
            get {
                return this.DOJField;
            }
            set {
                if ((this.DOJField.Equals(value) != true)) {
                    this.DOJField = value;
                    this.RaisePropertyChanged("DOJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpFirstName {
            get {
                return this.EmpFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpFirstNameField, value) != true)) {
                    this.EmpFirstNameField = value;
                    this.RaisePropertyChanged("EmpFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpID {
            get {
                return this.EmpIDField;
            }
            set {
                if ((this.EmpIDField.Equals(value) != true)) {
                    this.EmpIDField = value;
                    this.RaisePropertyChanged("EmpID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpLastName {
            get {
                return this.EmpLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpLastNameField, value) != true)) {
                    this.EmpLastNameField = value;
                    this.RaisePropertyChanged("EmpLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((this.PhoneField.Equals(value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeEdit", Namespace="http://schemas.datacontract.org/2004/07/HRMDAL.Entites")]
    [System.SerializableAttribute()]
    public partial class EmployeeEdit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AadharNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlternateEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BankACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlodGrpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCaddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCcityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CCpincodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCstateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurntShifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DrivingLCNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EmergncyPhneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FatherNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstAppField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificationMarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritalStusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotherNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotherTongueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PCaddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PCcityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PCpincodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PCstateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PFnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PanNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReligionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RprtigMgrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecndAppField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeekOFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AadharNo {
            get {
                return this.AadharNoField;
            }
            set {
                if ((this.AadharNoField.Equals(value) != true)) {
                    this.AadharNoField = value;
                    this.RaisePropertyChanged("AadharNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternateEmail {
            get {
                return this.AlternateEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.AlternateEmailField, value) != true)) {
                    this.AlternateEmailField = value;
                    this.RaisePropertyChanged("AlternateEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BankAC {
            get {
                return this.BankACField;
            }
            set {
                if ((this.BankACField.Equals(value) != true)) {
                    this.BankACField = value;
                    this.RaisePropertyChanged("BankAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlodGrp {
            get {
                return this.BlodGrpField;
            }
            set {
                if ((object.ReferenceEquals(this.BlodGrpField, value) != true)) {
                    this.BlodGrpField = value;
                    this.RaisePropertyChanged("BlodGrp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCaddr {
            get {
                return this.CCaddrField;
            }
            set {
                if ((object.ReferenceEquals(this.CCaddrField, value) != true)) {
                    this.CCaddrField = value;
                    this.RaisePropertyChanged("CCaddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCcity {
            get {
                return this.CCcityField;
            }
            set {
                if ((object.ReferenceEquals(this.CCcityField, value) != true)) {
                    this.CCcityField = value;
                    this.RaisePropertyChanged("CCcity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CCpincode {
            get {
                return this.CCpincodeField;
            }
            set {
                if ((this.CCpincodeField.Equals(value) != true)) {
                    this.CCpincodeField = value;
                    this.RaisePropertyChanged("CCpincode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCstate {
            get {
                return this.CCstateField;
            }
            set {
                if ((object.ReferenceEquals(this.CCstateField, value) != true)) {
                    this.CCstateField = value;
                    this.RaisePropertyChanged("CCstate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurntShif {
            get {
                return this.CurntShifField;
            }
            set {
                if ((object.ReferenceEquals(this.CurntShifField, value) != true)) {
                    this.CurntShifField = value;
                    this.RaisePropertyChanged("CurntShif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dept {
            get {
                return this.DeptField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptField, value) != true)) {
                    this.DeptField = value;
                    this.RaisePropertyChanged("Dept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DrivingLCNo {
            get {
                return this.DrivingLCNoField;
            }
            set {
                if ((this.DrivingLCNoField.Equals(value) != true)) {
                    this.DrivingLCNoField = value;
                    this.RaisePropertyChanged("DrivingLCNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EmergncyPhne {
            get {
                return this.EmergncyPhneField;
            }
            set {
                if ((this.EmergncyPhneField.Equals(value) != true)) {
                    this.EmergncyPhneField = value;
                    this.RaisePropertyChanged("EmergncyPhne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpID {
            get {
                return this.EmpIDField;
            }
            set {
                if ((this.EmpIDField.Equals(value) != true)) {
                    this.EmpIDField = value;
                    this.RaisePropertyChanged("EmpID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((this.ExpiryDateField.Equals(value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherName {
            get {
                return this.FatherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherNameField, value) != true)) {
                    this.FatherNameField = value;
                    this.RaisePropertyChanged("FatherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstApp {
            get {
                return this.FirstAppField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstAppField, value) != true)) {
                    this.FirstAppField = value;
                    this.RaisePropertyChanged("FirstApp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificationMark {
            get {
                return this.IdentificationMarkField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificationMarkField, value) != true)) {
                    this.IdentificationMarkField = value;
                    this.RaisePropertyChanged("IdentificationMark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((this.IssueDateField.Equals(value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStus {
            get {
                return this.MaritalStusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStusField, value) != true)) {
                    this.MaritalStusField = value;
                    this.RaisePropertyChanged("MaritalStus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotherName {
            get {
                return this.MotherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MotherNameField, value) != true)) {
                    this.MotherNameField = value;
                    this.RaisePropertyChanged("MotherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotherTongue {
            get {
                return this.MotherTongueField;
            }
            set {
                if ((object.ReferenceEquals(this.MotherTongueField, value) != true)) {
                    this.MotherTongueField = value;
                    this.RaisePropertyChanged("MotherTongue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PCaddr {
            get {
                return this.PCaddrField;
            }
            set {
                if ((object.ReferenceEquals(this.PCaddrField, value) != true)) {
                    this.PCaddrField = value;
                    this.RaisePropertyChanged("PCaddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PCcity {
            get {
                return this.PCcityField;
            }
            set {
                if ((object.ReferenceEquals(this.PCcityField, value) != true)) {
                    this.PCcityField = value;
                    this.RaisePropertyChanged("PCcity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PCpincode {
            get {
                return this.PCpincodeField;
            }
            set {
                if ((this.PCpincodeField.Equals(value) != true)) {
                    this.PCpincodeField = value;
                    this.RaisePropertyChanged("PCpincode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PCstate {
            get {
                return this.PCstateField;
            }
            set {
                if ((object.ReferenceEquals(this.PCstateField, value) != true)) {
                    this.PCstateField = value;
                    this.RaisePropertyChanged("PCstate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PFno {
            get {
                return this.PFnoField;
            }
            set {
                if ((this.PFnoField.Equals(value) != true)) {
                    this.PFnoField = value;
                    this.RaisePropertyChanged("PFno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PanNo {
            get {
                return this.PanNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PanNoField, value) != true)) {
                    this.PanNoField = value;
                    this.RaisePropertyChanged("PanNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNo {
            get {
                return this.PassportNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportNoField, value) != true)) {
                    this.PassportNoField = value;
                    this.RaisePropertyChanged("PassportNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Religion {
            get {
                return this.ReligionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReligionField, value) != true)) {
                    this.ReligionField = value;
                    this.RaisePropertyChanged("Religion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RprtigMgr {
            get {
                return this.RprtigMgrField;
            }
            set {
                if ((object.ReferenceEquals(this.RprtigMgrField, value) != true)) {
                    this.RprtigMgrField = value;
                    this.RaisePropertyChanged("RprtigMgr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecndApp {
            get {
                return this.SecndAppField;
            }
            set {
                if ((object.ReferenceEquals(this.SecndAppField, value) != true)) {
                    this.SecndAppField = value;
                    this.RaisePropertyChanged("SecndApp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WeekOF {
            get {
                return this.WeekOFField;
            }
            set {
                if ((object.ReferenceEquals(this.WeekOFField, value) != true)) {
                    this.WeekOFField = value;
                    this.RaisePropertyChanged("WeekOF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpSea.IEmpSea")]
    public interface IEmpSea {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpSea/EmpSearch", ReplyAction="http://tempuri.org/IEmpSea/EmpSearchResponse")]
        System.Collections.Generic.List<HumanResourceApplication.EmpSea.EmployeeSearch> EmpSearch(int EmpID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpSea/EmpSearchName", ReplyAction="http://tempuri.org/IEmpSea/EmpSearchNameResponse")]
        System.Collections.Generic.List<HumanResourceApplication.EmpSea.EmployeeSearch> EmpSearchName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpSea/RetriveDesignation", ReplyAction="http://tempuri.org/IEmpSea/RetriveDesignationResponse")]
        System.Collections.Generic.List<HumanResourceApplication.EmpSea.EmlpoyeeSeachEditEmp> RetriveDesignation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpSea/RetriveDepartment", ReplyAction="http://tempuri.org/IEmpSea/RetriveDepartmentResponse")]
        System.Collections.Generic.List<HumanResourceApplication.EmpSea.EmlpoyeeSeachEditEmp> RetriveDepartment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpSea/RetriveEmpID", ReplyAction="http://tempuri.org/IEmpSea/RetriveEmpIDResponse")]
        System.Collections.Generic.List<HumanResourceApplication.EmpSea.Salary> RetriveEmpID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpSea/SalaryGrid", ReplyAction="http://tempuri.org/IEmpSea/SalaryGridResponse")]
        System.Collections.Generic.List<HumanResourceApplication.EmpSea.Employee> SalaryGrid(int EmpID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpSea/CheckPanCardIDExist", ReplyAction="http://tempuri.org/IEmpSea/CheckPanCardIDExistResponse")]
        int CheckPanCardIDExist(string PanCardID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpSea/EmpSearchDepDes", ReplyAction="http://tempuri.org/IEmpSea/EmpSearchDepDesResponse")]
        System.Collections.Generic.List<HumanResourceApplication.EmpSea.EmployeeSearch> EmpSearchDepDes(string department, string desgnation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpSea/AddEditEmployee", ReplyAction="http://tempuri.org/IEmpSea/AddEditEmployeeResponse")]
        void AddEditEmployee(HumanResourceApplication.EmpSea.EmployeeEdit emplyEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpSea/ViewDetail", ReplyAction="http://tempuri.org/IEmpSea/ViewDetailResponse")]
        HumanResourceApplication.EmpSea.EmployeeEdit ViewDetail(int EmpID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpSea/EmployUpdate", ReplyAction="http://tempuri.org/IEmpSea/EmployUpdateResponse")]
        void EmployUpdate(HumanResourceApplication.EmpSea.EmployeeEdit emplyEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpSea/CheckEmpIDEdit", ReplyAction="http://tempuri.org/IEmpSea/CheckEmpIDEditResponse")]
        int CheckEmpIDEdit(int EmpID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpSeaChannel : HumanResourceApplication.EmpSea.IEmpSea, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpSeaClient : System.ServiceModel.ClientBase<HumanResourceApplication.EmpSea.IEmpSea>, HumanResourceApplication.EmpSea.IEmpSea {
        
        public EmpSeaClient() {
        }
        
        public EmpSeaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpSeaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpSeaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpSeaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<HumanResourceApplication.EmpSea.EmployeeSearch> EmpSearch(int EmpID) {
            return base.Channel.EmpSearch(EmpID);
        }
        
        public System.Collections.Generic.List<HumanResourceApplication.EmpSea.EmployeeSearch> EmpSearchName(string name) {
            return base.Channel.EmpSearchName(name);
        }
        
        public System.Collections.Generic.List<HumanResourceApplication.EmpSea.EmlpoyeeSeachEditEmp> RetriveDesignation() {
            return base.Channel.RetriveDesignation();
        }
        
        public System.Collections.Generic.List<HumanResourceApplication.EmpSea.EmlpoyeeSeachEditEmp> RetriveDepartment() {
            return base.Channel.RetriveDepartment();
        }
        
        public System.Collections.Generic.List<HumanResourceApplication.EmpSea.Salary> RetriveEmpID() {
            return base.Channel.RetriveEmpID();
        }
        
        public System.Collections.Generic.List<HumanResourceApplication.EmpSea.Employee> SalaryGrid(int EmpID) {
            return base.Channel.SalaryGrid(EmpID);
        }
        
        public int CheckPanCardIDExist(string PanCardID) {
            return base.Channel.CheckPanCardIDExist(PanCardID);
        }
        
        public System.Collections.Generic.List<HumanResourceApplication.EmpSea.EmployeeSearch> EmpSearchDepDes(string department, string desgnation) {
            return base.Channel.EmpSearchDepDes(department, desgnation);
        }
        
        public void AddEditEmployee(HumanResourceApplication.EmpSea.EmployeeEdit emplyEdit) {
            base.Channel.AddEditEmployee(emplyEdit);
        }
        
        public HumanResourceApplication.EmpSea.EmployeeEdit ViewDetail(int EmpID) {
            return base.Channel.ViewDetail(EmpID);
        }
        
        public void EmployUpdate(HumanResourceApplication.EmpSea.EmployeeEdit emplyEdit) {
            base.Channel.EmployUpdate(emplyEdit);
        }
        
        public int CheckEmpIDEdit(int EmpID) {
            return base.Channel.CheckEmpIDEdit(EmpID);
        }
    }
}
